### ISSUE TITLE
Process regular expressions in paths

### ISSUE THREAD

**Issue by cerrussell** [AppThreat/atom-tools#16]
### Tasks
- [ ] Identify in python
    - [x] Replace named groups
    - [ ] Look up parameter name when groups not named
    - [ ] Interpret regex to create schema for the parameter
- [ ] Identify in java
    - [ ] Replace named groups
    - [ ] Look up parameter name when groups not named
    - [ ] Interpret regex to create schema for the parameter
- [ ] Identify in javascript
    - [ ] Replace named groups
    - [ ] Look up parameter name when groups not named
    - [ ] Interpret regex to create schema for the parameter

### Examples
Sample endpoint with regex: `/(?P<organization_slug>[^\/]+)/(?P<project_slug>[^\/]+)/events/(?P<event_id>(?:\d+|[A-Fa-f0-9]{32}))/`
Desired output path: `/{organization_slug}/{project_slug}/events/{event_id}`
We could then determine the following schemas, then include them as refs for the endpoint schema
```
  "organization_slug": {
    "type": "string",
    "pattern": "[^\/]+"
  },
  "project_slug": {
    "type": "string",
    "pattern": "[^\/]+"
  },
  "event_id": {
    "type": "string",
    "minLength": 32,
    "maxLength": 32,
    "pattern": "(?:\\d+|[A-Fa-f0-9]{32})"
  }
``` 
Sample endpoint with regex: `/api/(?<globalCode>[\d]{2})-(?<nationalCode>[\d]{5,7})/org-(?<number>[\d]{6,})`:
Desired output path: `/api/{globalCode}-{nationalCode}/org-{number}`
Schemas:
```
  "globalCode": {
    "type": "integer",
    "minimum": 2,
    "maximum": 2
  },
  "nationalCode": {
    "type": "integer",
    "minimum": 5,
    "maximum": 7
  },
  "number": {
    "type": "integer",
    "minimum": 6,
  }
``` 
Sample endpoint with regex: `/share/(?:group|issue)/{share_id}`
Desired output path: `/share/{param}/{share_id}`
Schemas:
```
  "param": {
    "type": "string",
    "enum": ["group", "issue"]
  }
```
